In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df1=pd.read_csv("2018_Best_Dtypes.csv")
display(df1)

Column    Dtype
0     Flow Duration    int32
1      Tot Fwd Pkts    int32
2      Tot Bwd Pkts    int32
3   TotLen Fwd Pkts    int32
4   TotLen Bwd Pkts    int32
..              ...      ...
64        Idle Mean  float32
65         Idle Std  float32
66         Idle Max    int32
67         Idle Min    int32
68            Label   object

[69 rows x 2 columns]

In [24]:
df1.shape

(69, 2)

In [4]:
df1["Column"][2]

'Tot Bwd Pkts'

In [25]:
df1.head()

Column  Dtype
0    Flow Duration  int32
1     Tot Fwd Pkts  int32
2     Tot Bwd Pkts  int32
3  TotLen Fwd Pkts  int32
4  TotLen Bwd Pkts  int32

In [26]:
df1.tail()

Column    Dtype
64  Idle Mean  float32
65   Idle Std  float32
66   Idle Max    int32
67   Idle Min    int32
68   category   object

In [7]:
df1.loc[68,"Column"]="category"

In [28]:
df1.tail()

Column    Dtype
64  Idle Mean  float32
65   Idle Std  float32
66   Idle Max    int32
67   Idle Min    int32
68   category   object

In [27]:
dict1={}
for i in range(df1.shape[0]):
    dict1[df1["Column"][i]]=df1["Dtype"][i]
print(dict1)

{'Flow Duration': 'int32', 'Tot Fwd Pkts': 'int32', 'Tot Bwd Pkts': 'int32', 'TotLen Fwd Pkts': 'int32', 'TotLen Bwd Pkts': 'int32', 'Fwd Pkt Len Max': 'int32', 'Fwd Pkt Len Min': 'int16', 'Fwd Pkt Len Mean': 'float16', 'Fwd Pkt Len Std': 'float16', 'Bwd Pkt Len Max': 'int32', 'Bwd Pkt Len Min': 'int16', 'Bwd Pkt Len Mean': 'float16', 'Bwd Pkt Len Std': 'float16', 'Flow Byts/s': 'float32', 'Flow Pkts/s': 'float32', 'Flow IAT Mean': 'float32', 'Flow IAT Std': 'float32', 'Flow IAT Max': 'int32', 'Flow IAT Min': 'int32', 'Fwd IAT Tot': 'int32', 'Fwd IAT Mean': 'float32', 'Fwd IAT Std': 'float32', 'Fwd IAT Max': 'int32', 'Fwd IAT Min': 'int32', 'Bwd IAT Tot': 'int32', 'Bwd IAT Mean': 'float32', 'Bwd IAT Std': 'float32', 'Bwd IAT Max': 'int32', 'Bwd IAT Min': 'int32', 'Fwd PSH Flags': 'int8', 'Fwd URG Flags': 'int8', 'Fwd Header Len': 'int32', 'Bwd Header Len': 'int32', 'Fwd Pkts/s': 'float32', 'Bwd Pkts/s': 'float32', 'Pkt Len Min': 'int16', 'Pkt Len Max': 'int32', 'Pkt Len Mean': 'float16

In [9]:
df2=pd.read_csv("Data10.csv",dtype=dict1)
df2.head()

Flow Duration  Tot Fwd Pkts  Tot Bwd Pkts  TotLen Fwd Pkts  \
0      119646801            17            16              597   
1            375             2             1               38   
2            281             3             0               46   
3       99999555             2             2               16   
4       10070086             4             4              379   

   TotLen Bwd Pkts  Fwd Pkt Len Max  Fwd Pkt Len Min  Fwd Pkt Len Mean  \
0              768              293                0         35.125000   
1                0               38                0         19.000000   
2                0               46                0         15.335938   
3                0                8                8          8.000000   
4              408              379                0         94.750000   

   Fwd Pkt Len Std  Bwd Pkt Len Max  ...  Fwd Seg Size Min  Active Mean  \
0          97.0625              384  ...                20      45580.5   
1          26.8750                0  ...                20          0.0   
2          26.5625                0  ...                20          0.0   
3           0.0000                0  ...                32          1.0   
4         189.5000              408  ...                20          0.0   

     Active Std  Active Max  Active Min   Idle Mean     Idle Std  Idle Max  \
0  32287.847656      131880       32165   9922286.0  281712.5625  10014561   
1      0.000000           0           0         0.0       0.0000         0   
2      0.000000           0           0         0.0       0.0000         0   
3      0.000000           1           1  99999552.0       0.0000  99999553   
4      0.000000           0           0         0.0       0.0000         0   

   Idle Min  category  
0   9030908         0  
1         0         0  
2         0         0  
3  99999553         4  
4         0         0  

[5 rows x 69 columns]

In [29]:
memoryUsageInMB=df2.memory_usage(deep=True).sum()/(1024**2) 
print("Memory usage of the DataFrame="+str(f"{memoryUsageInMB:.2f}")+"MB")

Memory usage of the DataFrame=267.22MB


In [11]:
df2["category"].value_counts()

0    901347
3     77595
4     19657
1     14453
5     11382
2      9410
6        87
Name: category, dtype: int64

In [12]:
X=df2.drop(columns=["category"])
y=df2["category"]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,stratify=y,random_state=42)
#stratify=y->Uses Class Label y for Stratification
print("X_train Shape=",X_train.shape)
print("X_test Shape=",X_test.shape)
print("y_train Shape=",y_train.shape)
print("y_test Shape=",y_test.shape)

X_train Shape= (723751, 68)
X_test Shape= (310180, 68)
y_train Shape= (723751,)
y_test Shape= (310180,)


In [30]:
y_train.value_counts()

0    630942
3     54317
4     13760
1     10117
5      7967
2      6587
6        61
Name: category, dtype: int64

In [15]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [16]:
from sklearn.decomposition import PCA
pca=PCA(n_components=0.95,random_state=42)
X_train_pca=pca.fit_transform(X_train_scaled)
X_test_pca=pca.transform(X_test_scaled)

In [17]:
print(pca.explained_variance_ratio_)
arr=pca.explained_variance_ratio_
for i in range(2):
    if(i==0):
        print(str(i+1)+"st PCA Column variance=",arr[i])
    if(i==1):
        print(str(i+1)+"nd PCA Column variance=",arr[i])

[0.38561526 0.20829335 0.11630425 0.07219939 0.06079518 0.0462549
 0.03275466 0.02329973 0.01637854]
1st PCA Column variance= 0.3856152608175302
2nd PCA Column variance= 0.20829334522409826


In [18]:
from sklearn.tree import DecisionTreeClassifier
import timeit

In [31]:
model=DecisionTreeClassifier()
y_train=y_train.astype('int')
y_test=y_test.astype('int')
trainingstarttime=timeit.default_timer()
model.fit(X_train_pca,y_train)
trainingtime=timeit.default_timer()-trainingstarttime

In [32]:
testingstarttime=timeit.default_timer()
y_pred=model.predict(X_test_pca)
testingtime=timeit.default_timer()-testingstarttime

In [33]:
print("Training Time=",trainingtime,"seconds")
print("Testing Time=",testingtime,"seconds")

Training Time= 51.274236700031906 seconds
Testing Time= 0.18524030002299696 seconds


In [34]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,fbeta_score
conf_matrix=confusion_matrix(y_test,y_pred)

accuracy=accuracy_score(y_test,y_pred)
precision=precision_score(y_test,y_pred,average='weighted')
recall=recall_score(y_test,y_pred,average='weighted')
f2_score=fbeta_score(y_test,y_pred,beta=2,average='weighted')

print("Confusion Matrix=\n",conf_matrix)
print("Accuracy=",accuracy)
print("Precision=",precision)
print("Recall=",recall)
print("F-2 Score=",f2_score)

Confusion Matrix=
 [[267475     17      0     38     25   2839     11]
 [    20   4316      0      0      0      0      0]
 [     1      0   2820      0      2      0      0]
 [    15      0      0  23263      0      0      0]
 [    17      0      0      0   5880      0      0]
 [  3044      0      0      2      0    368      1]
 [     6      2      0      0      0      0     18]]
Accuracy= 0.9805274356825069
Precision= 0.9799456315656804
Recall= 0.9805274356825069
F-2 Score= 0.9804100502365634
